### ISSUE TITLE
Yaml side is cleared after set-header/body/property/exchange-pattern inserted

### ISSUE THREAD

**Issue by unsortedhashsets** [KaotoIO/kaoto-ui#1351]
### Describe the Bug

After any of the EIP  set-header/body/property/exchange-pattern inserting, yaml side is rerendered to the default state.

Faced the issue during preparing E2E tests ([Issue-1297](https://github.com/KaotoIO/kaoto-ui/issues/1297#issue-1593940954)). Initially thought the problem was on the [step-extension-repository](https://github.com/KaotoIO/step-extension-repository) side but found that there is no `set-exchange-pattern` extension.

Init state: 

```
- from:
    uri: timer:null
    steps:
    - to:
        uri: log:null
```

### Steps to Reproduce the Bug or Issue

1. Create pipeline: timer(start) -> log(end/action)
2. Open YAML Source Code
3. Insert any of set-* steps (EIPs)
4. See that the Source code is rerendered to the default state: `Start editing`

### Screenshots or Videos

Init State:
![Screenshot from 2023-03-02 17-16-17](https://user-images.githubusercontent.com/46084942/222486654-8ad283b5-7687-4e51-9d34-252a49510373.png)

After set-* step inserted:
![Screenshot from 2023-03-02 17-16-30](https://user-images.githubusercontent.com/46084942/222486787-afa82647-0cfe-4edb-9dae-29a3ac075364.png)

### Platform

- OS: [Red Hat Enterprise Linux 8.6]
- Browser: [Chrome]
- Version: [110.0.5481.177]

**Comment by mmelko** [comment]
@Delawen @unsortedhashsets this is probably a backend issue as we've seen in the past: 

``` Parser class io.kaoto.backend.api.service.deployment.generator.camelroute.CamelRouteDeploymentGeneratorService_ClientProxythrew an unexpected error. : java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "io.kaoto.backend.model.step.Step.getParameters()" is null
        at io.kaoto.backend.KamelPopulator.getExpression(KamelPopulator.java:473)
        at io.kaoto.backend.KamelPopulator.processStep(KamelPopulator.java:335)
        at io.kaoto.backend.KamelPopulator.getFlow(KamelPopulator.java:262)
        at io.kaoto.backend.model.deployment.camelroute.CamelRoute.<init>(CamelRoute.java:26)
        at io.kaoto.backend.api.service.deployment.generator.camelroute.CamelRouteDeploymentGeneratorService.parse(CamelRouteDeploymentGeneratorService.java:76)
        at io.kaoto.backend.api.service.deployment.generator.camelroute.CamelRouteDeploymentGeneratorService_ClientProxy.parse(Unknown Source)
        at io.kaoto.backend.api.service.deployment.DeploymentService.crd(DeploymentService.java:86)
        at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass.crd$$superforward1(Unknown Source)
        at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
        at io.kaoto.backend.api.service.deployment.DeploymentService_Subclass.crd(Unknown Source)
        at io.kaoto.backend.api.service.deployment.DeploymentService_ClientProxy.crd(Unknown Source)
        at io.kaoto.backend.api.resource.v1.IntegrationsResource.cdr(IntegrationsResource.java:85)
        at io.kaoto.backend.api.resource.v1.IntegrationsResource_ClientProxy.cdr(Unknown Source)
        at io.kaoto.backend.api.resource.v1.IntegrationsResource$quarkusrestinvoker$cdr_bda4f3154fddee7031592f0b55e0f34abe335178.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Delawen** [comment]
If you add the example on that issue, we can close this one as duplicated.

**Comment by mmelko** [comment]
to me this sounds like different thing: `Step.getParameters()" is null` main difference here is that that's to that exception we are getting empty response from the backend and the source is wiped out. So let's see if your fix for https://github.com/KaotoIO/kaoto-backend/issues/479 will help with this-one too.

**Comment by igarashitm** [comment]
Possibly this had been already fixed with https://github.com/KaotoIO/kaoto-backend/issues/512 - it doesn't reproduce for me now. @unsortedhashsets can you try again with the latest?

**Comment by unsortedhashsets** [comment]
@igarashitm Hi, thanks for the information. 
Yes all set-* EIPs work fine now, I will prepare PR with an E2E test update (there was one blocked test)

**Comment by unsortedhashsets** [comment]
I close this bug as resolved with the [Issue-512]( https://github.com/KaotoIO/kaoto-backend/issues/512)
