### ISSUE TITLE
Unmarshal and marshal config panel "Field not found in schema: "properties"

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1563]
### Describe the Bug

In UI:
```
Something went wrong:
Field not found in schema: "properties"
```

in console log:

```
react-dom.production.min.js:189 Invariant Violation: Field not found in schema: "properties"
    at invariant (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/448.js:13211:15)
    at fieldInvariant (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/330.js:5038:22)
    at http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/330.js:5141:17
    at Array.reduce (<anonymous>)
    at CustomJsonSchemaBridge.getField (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/330.js:5123:51)
    at CustomJsonSchemaBridge.getField (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/448.js:19439:29)
    at CustomJsonSchemaBridge.memoized [as getField] (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/681.js:12033:23)
    at useField (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/693.js:6999:34)
    at AutoField (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/693.js:7118:35)
    at Xh (http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/935.js:173:137)
```

### Steps to Reproduce the Bug or Issue

1. Open Source code editor
2. Add a step
3. add an unmarshal or marshal
4. Select Unmarshal or Marshal
5. --> error in config panel

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/227974367-46bd4aa1-b00f-4979-b512-e91d588ecc07.png)

### Platform

OperateFirst

**Comment by igarashitm** [comment]
https://github.com/KaotoIO/camel-component-metadata/pull/14 avoids config tab from crashing, but marshal/unmarshal are still unusable due to https://github.com/KaotoIO/kaoto-backend/issues/595
