### ISSUE TITLE
`.spec.definition.title` is null for a new Kamelet which causes an exception in the backend

### ISSUE THREAD

**Issue by mkralik3** [KaotoIO/kaoto-ui#1803]
### Describe the Bug

`.spec.definition.title` is null (`title: null`, without surrounding any apostrophes) for an initial empty Kamelet which causes an exception[1] in the backend when the code is synced. When I change it to the empty string `title: ''`, the error is not shown.

If this option for setting the title is not in the UI, we can use there the same string as in the `.metadata.name`.
[1]
```
2023-05-16 13:13:12,817 WARN  [io.kao.bac.api.res.v1.IntegrationsResource] (executor-thread-0) Parser class io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService_ClientProxythrew an unexpected error.: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteDeserializer.deserialize(CamelRouteDeserializer.java:32)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteDeserializer.deserialize(CamelRouteDeserializer.java:19)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService.getCamelRoute(CamelRouteStepParserService.java:119)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService.appliesTo(CamelRouteStepParserService.java:112)
	at io.kaoto.backend.api.service.step.parser.camelroute.CamelRouteStepParserService_ClientProxy.appliesTo(Unknown Source)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource.integration(IntegrationsResource.java:132)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource_ClientProxy.integration(Unknown Source)
	at io.kaoto.backend.api.resource.v1.IntegrationsResource$quarkusrestinvoker$integration_a2f8369bb7dcf7cb17b1bb4f8473b027a51694dd.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@19.0.1/java.lang.Thread.run(Thread.java:1589)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

2023-05-16 13:13:12,820 WARN  [io.kao.bac.api.res.v1.IntegrationsResource] (executor-thread-0) Gurl, the DSL you gave me is so wrong. This is a Kamelet not a null
```

### Steps to Reproduce the Bug or Issue

1. Open KaotoUI
2. In the settings, change to Kamelet
3. Open the source code editor and click on `Sync your code`
4. The error is shown in the backend log

### Platform

- OS: Linux
- Browser: Firefox
- Version: 1.0.0 / main branch

**Comment by mkralik3** [comment]
Closed in favor to https://github.com/KaotoIO/kaoto-ui/issues/1803

**Comment by mkralik3** [comment]
Reopened after discusion. The original issue is not a bug ( see https://github.com/KaotoIO/kaoto-backend/issues/662 ) , however, the question is why the dsl query param is null after the code in codeviewer is sync (with the example Kamelet).

**Comment by mkralik3** [comment]
There are two requests, first without query param and next with query param
param
but it doesn't matter. The backend should be able to properly decide which DSL is used without that param and shouldn't throw any exception so I am closing this issue and reopening the backend one.
