### ISSUE TITLE
e2e test failure

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#2011]
### Describe the Bug

Currently 2 e2e tests are failing on main
cf. https://github.com/KaotoIO/kaoto-ui/actions/runs/5338384015/jobs/9675795070

<details>
<summary>04-source_code/source_code.cy.js</summary> 

```
source code and drag and drop
    1) "before each" hook for "loads the YAML editor and synchronizes steps with visualization"


  0 passing (21s)
  1 failing

  1) source code and drag and drop
       "before each" hook for "loads the YAML editor and synchronizes steps with visualization":
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 2nd request to the route: `getViewDefinitions`. No request ever occurred.

https://on.cypress.io/wait

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `source code and drag and drop`
      at cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:164500:18)
      at Object.errByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:164555:10)
      at checkForXhr (http://localhost:1337/__cypress/runner/cypress_runner.js:151419:92)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:151442:28)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:156384:65)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:155825:14)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:16[781](https://github.com/KaotoIO/kaoto-ui/actions/runs/5338384015/jobs/9675795070#step:6:785):10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/kaoto-ui-commands/editor.js:57:7)
```

</details>

<details>

<summary>08-code-editor-actions/code_editor_actions.cy.js</summary>

```
  editing properties
    1) User adds step to the YAML
    2) User removes step from the YAML
    3) User edits step in the YAML
    ✓ User Deletes branch in the YAML (9844ms)
    ✓ User Add a new branch in the YAML (15969ms)
    ✓ User undoes a change they saved, syncs with canvas (10744ms)
    ✓ User uploads YAML file, syncs with canvas (5419ms)


  4 passing (2m)
  3 failing

  1) editing properties
       User adds step to the YAML:
     AssertionError: Timed out retrying after 8000ms: Expected to find element: `[data-testid="viz-step-insert-field-action"]`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/08-code-editor-actions/code_editor_actions.cy.js:26:59)

  2) editing properties
       User removes step from the YAML:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 3rd request to the route: `getViewDefinitions`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:164500:18)
      at Object.errByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:164555:10)
      at checkForXhr (http://localhost:1337/__cypress/runner/cypress_runner.js:151419:92)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:151442:28)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:156384:65)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:155825:14)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/kaoto-ui-commands/editor.js:57:7)

  3) editing properties
       User edits step in the YAML:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 3rd request to the route: `getViewDefinitions`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:164500:18)
      at Object.errByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:164555:10)
      at checkForXhr (http://localhost:1337/__cypress/runner/cypress_runner.js:151419:92)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:151442:28)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:156384:65)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:155825:14)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/kaoto-ui-commands/editor.js:57:7)
```
</details>

### Steps to Reproduce the Bug or Issue

1. Run e2e tests

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by tplevko** [comment]
@igarashitm this was fixed in https://github.com/KaotoIO/kaoto-ui/pull/2009
I think this should be done and can be closed
