### ISSUE TITLE
E2E test failing after backend name/description fix

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#2130]
### Describe the Bug

https://github.com/KaotoIO/kaoto-ui/actions/runs/5520721506/jobs/10067923738#step:6:1362

```
Running:  08-code-editor-actions/code_editor_actions.cy.js                              (10 of 18)


  editing properties
    ✓ User adds step to the YAML (25[907](https://github.com/KaotoIO/kaoto-ui/actions/runs/5520721506/jobs/10067923738#step:6:911)ms)
    - User removes step from the YAML
    ✓ User edits step in the YAML (10930ms)
    ✓ User Deletes branch in the YAML (10127ms)
    1) User Add a new branch in the YAML
    2) User undoes a change they saved, syncs with canvas
    ✓ User uploads YAML file, syncs with canvas (6256ms)


  4 passing (2m)
  1 pending
  2 failing

  1) editing properties
       User Add a new branch in the YAML:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 3rd request to the route: `getViewDefinitions`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:164516:18)
      at Object.errByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:164571:10)
      at checkForXhr (http://localhost:1337/__cypress/runner/cypress_runner.js:151435:92)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:151458:28)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:156400:65)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:155841:14)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/kaoto-ui-commands/editor.js:72:7)

  2) editing properties
       User undoes a change they saved, syncs with canvas:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 3rd request to the route: `getViewDefinitions`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:164516:18)
      at Object.errByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:164571:10)
      at checkForXhr (http://localhost:1337/__cypress/runner/cypress_runner.js:151435:92)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:151458:28)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:156400:65)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:155841:14)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:1337/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/kaoto-ui-commands/editor.js:72:7)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        7                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 30 seconds                                                             │
  │ Spec Ran:     08-code-editor-actions/code_editor_actions.cy.js                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /__w/kaoto-ui/kaoto-ui/cypress/screenshots/08-code-editor-actions/code_editor_ac     (1280x720)
     tions.cy.js/editing properties -- User Add a new branch in the YAML (failed).png               
  -  /__w/kaoto-ui/kaoto-ui/cypress/screenshots/08-code-editor-actions/code_editor_ac     (1280x720)
     tions.cy.js/editing properties -- User undoes a change they saved, syncs with ca               
     nvas (failed).png                                                                              


  (Video)

  -  Started compressing: Compressing to 32 CRF                                                     
    Compression progress:  59%
  -  Finished compressing: 17 seconds                                                

  -  Video output: /__w/kaoto-ui/kaoto-ui/cypress/videos/08-code-editor-actions/code_editor_actions.cy.js.mp4
```

### Steps to Reproduce the Bug or Issue

1. `yarn e2e:headless`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by igarashitm** [comment]
It was just a coincidence, failing due to the backend fix for name/description. #2127 fixes this.
