### ISSUE TITLE
[VS Code] Modifying beans is not marking editor dirty

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#2133]
### Describe the Bug

Modifying beans is not marking editor dirty, it implies hthat the data configured can be lost if no othe rmodificatiosn are done and saved

### Steps to Reproduce the Bug or Issue

1. Open camel route in VS Code
2. Click on Beans
3. Provide some values
4. Close window
--> the editor is nto marked as dirty.
if closign and reopening the data is lost

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-ui/assets/1105127/44210a60-901d-4c40-805d-272874fb0720

### Platform

- Version: main branch for backend and UI

**Comment by igarashitm** [comment]
Sounds like the onBlur saving is not working inside vscode? do we need a save button then?

**Comment by apupier** [comment]
the source code editor inside Kaoto is updated:

https://github.com/KaotoIO/kaoto-ui/assets/1105127/fd557b46-6e6a-461a-8058-136ce957313e

(even if I do not know the internals of Kaoto UI, it leads me to think that it is not a problem with an onBlur listener)

**Comment by igarashitm** [comment]
OK that's right... makes me even puzzled

**Comment by apupier** [comment]
When opening the Beans modal, in console log there is:

```
react-dom.development.js:86 Warning: React does not recognize the `inputRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at TextInputBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:235809:9)
    at TextInput
    at div
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:236333:9)
    at FormGroup (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:233074:11)
    at TextField (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:15352:11)
    at Field (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:192580:97)
    at AutoField (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:192640:96)
    at div
    at form
    at FormBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:232912:11)
    at Form
    at AutoValidatedQuickPatternflyForm
    at div
    at StackItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231708:11)
    at div
    at Stack (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231678:11)
    at div
    at SplitItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231629:11)
    at div
    at Split (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231599:11)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:188918:5)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7184:30)
    at div
    at ModalBoxBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213347:11)
    at div
    at ModalBox (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213314:11)
    at div
    at FocusTrapBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226276:9)
    at div
    at Backdrop (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:202570:11)
    at ModalContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213586:11)
    at Modal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213172:9)
    at MetadataEditorModal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7971:32)
    at div
    at ToolbarItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:224010:11)
    at MetadataToolbarItems (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8084:73)
    at div
    at div
    at ToolbarContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223729:9)
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226368:9)
    at Toolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223561:9)
    at KaotoToolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6594:25)
    at section
    at PageSection (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:216425:11)
    at main
    at div
    at Page (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:215911:9)
    at div
    at FlexItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231263:11)
    at div
    at Flex (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231229:11)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206627:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206692:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206593:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206487:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6523:11)
    at Dashboard (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9151:108)
    at Route (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191053:29)
    at RouteWithTitleUpdates (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9574:22)
    at Switch (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191255:29)
    at LastLocationProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190185:47)
    at C (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191310:37)
    at AppRoutes
    at div
    at PanelBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217107:11)
    at Panel
    at AppLayout (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9114:22)
    at Suspense
    at Router (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190672:30)
    at HashRouter (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:189767:35)
    at AlertProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9272:26)
    at KogitoEditorIntegrationProviderInternal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8910:52)
    at CapabilitiesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9450:33)
    at https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8692:94
    at div
    at EditorEnvelopeViewRef (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:197815:42)
    at I18nDictionariesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:199572:55)
```

and

```
react-dom.development.js:86 Warning: React does not recognize the `labelIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at TextInputBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:235809:9)
    at TextInput
    at div
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:236333:9)
    at FormGroup (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:233074:11)
    at TextField (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:15352:11)
    at Field (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:192580:97)
    at AutoField (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:192640:96)
    at div
    at form
    at FormBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:232912:11)
    at Form
    at AutoValidatedQuickPatternflyForm
    at div
    at StackItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231708:11)
    at div
    at Stack (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231678:11)
    at div
    at SplitItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231629:11)
    at div
    at Split (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231599:11)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:188918:5)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7184:30)
    at div
    at ModalBoxBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213347:11)
    at div
    at ModalBox (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213314:11)
    at div
    at FocusTrapBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226276:9)
    at div
    at Backdrop (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:202570:11)
    at ModalContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213586:11)
    at Modal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213172:9)
    at MetadataEditorModal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7971:32)
    at div
    at ToolbarItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:224010:11)
    at MetadataToolbarItems (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8084:73)
    at div
    at div
    at ToolbarContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223729:9)
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226368:9)
    at Toolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223561:9)
    at KaotoToolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6594:25)
    at section
    at PageSection (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:216425:11)
    at main
    at div
    at Page (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:215911:9)
    at div
    at FlexItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231263:11)
    at div
    at Flex (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231229:11)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206627:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206692:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206593:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206487:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6523:11)
    at Dashboard (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9151:108)
    at Route (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191053:29)
    at RouteWithTitleUpdates (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9574:22)
    at Switch (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191255:29)
    at LastLocationProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190185:47)
    at C (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191310:37)
    at AppRoutes
    at div
    at PanelBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217107:11)
    at Panel
    at AppLayout (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9114:22)
    at Suspense
    at Router (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190672:30)
    at HashRouter (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:189767:35)
    at AlertProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9272:26)
    at KogitoEditorIntegrationProviderInternal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8910:52)
    at CapabilitiesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9450:33)
    at https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8692:94
    at div
    at EditorEnvelopeViewRef (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:197815:42)
    at I18nDictionariesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:199572:55)
 ```
 
 when clicking "Add a new" bean:
 ```
Warning: validateDOMNesting(...): <output> cannot appear as a child of <tbody>.
    at output
    at TrBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:21471:11)
    at Tr
    at tbody
    at TbodyBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:21100:11)
    at Tbody
    at table
    at TableComposableBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:21017:11)
    at TableComposable
    at div
    at InnerScrollContainer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:20943:11)
    at div
    at OuterScrollContainer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:20972:11)
    at TopmostArrayTable (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8412:445)
    at div
    at SplitItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231629:11)
    at div
    at Split (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231599:11)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:188918:5)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7184:30)
    at div
    at ModalBoxBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213347:11)
    at div
    at ModalBox (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213314:11)
    at div
    at FocusTrapBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226276:9)
    at div
    at Backdrop (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:202570:11)
    at ModalContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213586:11)
    at Modal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:213172:9)
    at MetadataEditorModal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7971:32)
    at div
    at ToolbarItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:224010:11)
    at MetadataToolbarItems (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8084:73)
    at div
    at div
    at ToolbarContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223729:9)
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226368:9)
    at Toolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:223561:9)
    at KaotoToolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6594:25)
    at section
    at PageSection (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:216425:11)
    at main
    at div
    at Page (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:215911:9)
    at div
    at FlexItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231263:11)
    at div
    at Flex (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:231229:11)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206627:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206692:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206593:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:206487:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6523:11)
    at Dashboard (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9151:108)
    at Route (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191053:29)
    at RouteWithTitleUpdates (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9574:22)
    at Switch (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191255:29)
    at LastLocationProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190185:47)
    at C (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191310:37)
    at AppRoutes
    at div
    at PanelBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217107:11)
    at Panel
    at AppLayout (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9114:22)
    at Suspense
    at Router (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:190672:30)
    at HashRouter (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:189767:35)
    at AlertProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9272:26)
    at KogitoEditorIntegrationProviderInternal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8910:52)
    at CapabilitiesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9450:33)
    at https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8692:94
    at div
    at EditorEnvelopeViewRef (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:197815:42)
    at I18nDictionariesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:199572:55)
```

No error when quitting the modal dialog
